import type { Metadata, Viewport } from "next";
import { Exo_2, Orbitron } from "next/font/google";
import { cookies } from "next/headers";
import { Analytics } from "@vercel/analytics/next";
import { DeferredToastProvider } from "@/components/layout/deferred-toast-provider";
import { ErrorReporter } from "@/components/telemetry/error-reporter";
import { JsonLd } from "@/components/ui/json-ld";
import { ScrollToTop } from "@/components/layout/scroll-to-top";
import { ServiceWorkerRegistration } from "@/components/pwa/service-worker-registration";
import { APPLE_SPLASH } from "@/lib/apple-splash.generated";
import "../styles/globals.css";
import {
  SITE_AUTHOR_LINKEDIN,
  SITE_AUTHOR_NAME,
  SITE_AUTHOR_URL,
  SITE_CANONICAL_URL,
  SITE_DESCRIPTION,
  SITE_KEYWORDS,
  SITE_LOGO_URL,
  SITE_NAME,
  SITE_ORG_SAME_AS,
} from "@/lib/seo";

// Self-hosted brand faces (globals.css declared these families for months but
// nothing ever loaded them — the site silently rendered in system fonts).
// display:swap + next/font's size-adjusted fallback keep CLS at ~0.
const orbitron = Orbitron({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-orbitron",
  // Not preloaded: the LCP hero text renders in Exo 2 — keeping this 41 KB
  // display face out of the pre-FCP critical window buys first paint time;
  // the size-adjusted fallback bounds the later swap shift.
  preload: false,
});
const exo2 = Exo_2({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-exo2",
});

const BASE_URL = SITE_CANONICAL_URL;
const ENABLE_VERCEL_ANALYTICS =
  Boolean(process.env.VERCEL) || process.env.NEXT_PUBLIC_ENABLE_VERCEL_ANALYTICS === "1";

export const viewport: Viewport = {
  // Match --color-bg and the manifest theme_color so browser chrome and the
  // installed-app title bar blend with the dark UI.
  themeColor: "#0F172A",
  // Required for env(safe-area-inset-*) so the bottom nav clears the iOS home indicator
  viewportFit: "cover",
};

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: "Stellaroid Earn",
    template: "%s | Stellaroid Earn",
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_AUTHOR_NAME, url: SITE_AUTHOR_URL }],
  keywords: SITE_KEYWORDS,
  alternates: { canonical: "/" },
  icons: {
    icon: [
      { url: "/favicon.png", type: "image/png", sizes: "32x32" },
      { url: "/favicon-48.png", type: "image/png", sizes: "48x48" },
      { url: "/logo.svg", type: "image/svg+xml" },
    ],
    apple: [{ url: "/apple-touch-icon.png", type: "image/png", sizes: "180x180" }],
  },
  appleWebApp: {
    capable: true,
    title: "Stellaroid Earn",
    // Translucent status bar over the dark glass header (paired with the
    // header's env(safe-area-inset-top) padding).
    statusBarStyle: "black-translucent",
    // Per-device launch screens so a cold standalone start paints the brand
    // tile instead of a blank flash. Generated by scripts/generate-splash.mjs.
    startupImage: [...APPLE_SPLASH],
  },
  openGraph: {
    type: "website",
    url: BASE_URL,
    siteName: "Stellaroid Earn",
    title: "Stellaroid Earn",
    description: SITE_DESCRIPTION,
    locale: "en_US",
    alternateLocale: "tl_PH",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "Stellaroid Earn",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Stellaroid Earn",
    description: SITE_DESCRIPTION,
    images: ["/opengraph-image"],
  },
};

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Stellaroid Earn",
  url: BASE_URL,
  logo: {
    "@type": "ImageObject",
    url: SITE_LOGO_URL,
    width: 512,
    height: 512,
  },
  description: SITE_DESCRIPTION,
  sameAs: SITE_ORG_SAME_AS,
  founder: {
    "@type": "Person",
    name: SITE_AUTHOR_NAME,
    url: SITE_AUTHOR_URL,
  },
};

const webAppJsonLd = [
  {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "Stellaroid Earn",
    url: BASE_URL,
    creator: {
      "@type": "Person",
      name: SITE_AUTHOR_NAME,
      url: SITE_AUTHOR_URL,
      sameAs: [SITE_AUTHOR_URL, SITE_AUTHOR_LINKEDIN],
    },
    description:
      "Stellaroid Earn links proof and payment on Stellar for certificates, completed work, and milestone approvals.",
    applicationCategory: "FinanceApplication",
    operatingSystem: "Web",
    // Free public testnet demo — feeds "what does it cost / do" generative answers.
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
      url: `${BASE_URL}/app`,
    },
    featureList: [
      "Anchor a certificate's SHA-256 hash on Stellar",
      "Verify credentials on-chain with an approved issuer",
      "Pay verified graduates instantly in XLM",
      "Public, wallet-free proof pages",
    ],
  },
  organizationJsonLd,
];

const authorProfileJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: SITE_AUTHOR_NAME,
  url: SITE_AUTHOR_URL,
  sameAs: [SITE_AUTHOR_LINKEDIN, SITE_AUTHOR_URL],
};

const webSiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: SITE_NAME,
  url: BASE_URL,
  description: SITE_DESCRIPTION,
  publisher: { "@type": "Organization", name: SITE_NAME, url: BASE_URL },
  // Proof lookup by hash — enables the sitelinks search box.
  potentialAction: {
    "@type": "SearchAction",
    target: {
      "@type": "EntryPoint",
      urlTemplate: `${BASE_URL}/proof/{hash}`,
    },
    "query-input": "required name=hash",
  },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const lang = cookieStore.get("stellaroid:locale")?.value === "tl" ? "tl" : "en";

  return (
    <html lang={lang} className={`${orbitron.variable} ${exo2.variable} font-sans`}>
      <body suppressHydrationWarning>
        {webAppJsonLd.map((schema, i) => (
          <JsonLd key={i} data={schema} />
        ))}
        <JsonLd data={webSiteJsonLd} />
        <JsonLd data={authorProfileJsonLd} />
        {children}
        <ScrollToTop />
        {ENABLE_VERCEL_ANALYTICS ? <Analytics /> : null}
        <DeferredToastProvider />
        <ServiceWorkerRegistration />
        <ErrorReporter />
      </body>
    </html>
  );
}
