// Regenerates the iOS launch-screen ("apple-touch-startup-image") set from
// public/logo-512.svg, plus a typed manifest consumed by app/layout.tsx.
// Usage: node scripts/generate-splash.mjs
//
// Each device needs a portrait + landscape image at its exact device-pixel
// resolution, matched by a media query on (device-width, device-height,
// -webkit-device-pixel-ratio, orientation). Design: the brand mark centered
// on a solid --color-bg tile, so it blends into the app's first paint.
import sharp from "sharp";
import { writeFileSync, mkdirSync } from "node:fs";

const BG = "#0F172A"; // --color-bg
const SOURCE = "public/logo-512.svg";
const OUT_DIR = "public/splash";

// Logical points (w, h in portrait) and device-pixel ratio. One row per unique
// (w, h, dpr) triple — devices that share a triple share a media query.
const DEVICES = [
  { name: "iphone-se", w: 375, h: 667, dpr: 2 },
  { name: "iphone-8plus", w: 414, h: 736, dpr: 3 },
  { name: "iphone-x", w: 375, h: 812, dpr: 3 },
  { name: "iphone-xr", w: 414, h: 896, dpr: 2 },
  { name: "iphone-xsmax", w: 414, h: 896, dpr: 3 },
  { name: "iphone-12", w: 390, h: 844, dpr: 3 },
  { name: "iphone-14plus", w: 428, h: 926, dpr: 3 },
  { name: "iphone-15", w: 393, h: 852, dpr: 3 },
  { name: "iphone-15plus", w: 430, h: 932, dpr: 3 },
  { name: "iphone-16pro", w: 402, h: 874, dpr: 3 },
  { name: "iphone-16promax", w: 440, h: 956, dpr: 3 },
  { name: "ipad-9-7", w: 768, h: 1024, dpr: 2 },
  { name: "ipad-10-2", w: 810, h: 1080, dpr: 2 },
  { name: "ipad-air", w: 820, h: 1180, dpr: 2 },
  { name: "ipad-pro-10-5", w: 834, h: 1112, dpr: 2 },
  { name: "ipad-pro-11", w: 834, h: 1194, dpr: 2 },
  { name: "ipad-pro-12-9", w: 1024, h: 1366, dpr: 2 },
];

async function splash(px, py, out) {
  const inner = Math.round(Math.min(px, py) * 0.26);
  const logo = await sharp(SOURCE)
    .resize(inner, inner, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();

  await sharp({
    create: { width: px, height: py, channels: 4, background: BG },
  })
    .composite([{ input: logo, gravity: "center" }])
    .png({ compressionLevel: 9 })
    .toFile(out);
}

function query(d, orientation) {
  return (
    `screen and (device-width: ${d.w}px) and (device-height: ${d.h}px) ` +
    `and (-webkit-device-pixel-ratio: ${d.dpr}) and (orientation: ${orientation})`
  );
}

mkdirSync(OUT_DIR, { recursive: true });

const entries = [];
for (const d of DEVICES) {
  const pw = d.w * d.dpr;
  const ph = d.h * d.dpr;
  const portrait = `${d.name}-portrait.png`;
  const landscape = `${d.name}-landscape.png`;

  await splash(pw, ph, `${OUT_DIR}/${portrait}`);
  await splash(ph, pw, `${OUT_DIR}/${landscape}`);

  entries.push({ url: `/splash/${portrait}`, media: query(d, "portrait") });
  entries.push({ url: `/splash/${landscape}`, media: query(d, "landscape") });
  console.log(`wrote ${d.name} (${pw}x${ph} + ${ph}x${pw})`);
}

const ts =
  `// GENERATED by scripts/generate-splash.mjs — do not edit by hand.\n` +
  `// Consumed by app/layout.tsx via metadata.appleWebApp.startupImage.\n` +
  `export const APPLE_SPLASH = ${JSON.stringify(entries, null, 2)} as const;\n`;

writeFileSync("src/lib/apple-splash.generated.ts", ts);
console.log(`wrote src/lib/apple-splash.generated.ts (${entries.length} entries)`);
